### ISSUE TITLE
A little credit where credit is due please

### ISSUE THREAD

**Issue by yereverluvinunclebert** [xyz32/timekeeper-evolution#1]
Please ensure a credit to my original artwork is prominently displayed somewhere. As programs are forked it does sometimes happen that the original artist can be forgotten. 

FYI - Joker created the plasmoid from my original widget art that you can see working here:  https://www.deviantart.com/yereverluvinuncleber/art/Steampunk-Orrery-Calendar-Clock-Yahoo-Widget-MkII-455720507

So, a credit please. Somewhere obvious and prominent and a link back to that page will do fine.

**Comment by xyz32** [comment]
Hi, thanks for the message.
As mention in the readme file I just took over Joker's work since he was no longer maintaining the code, or merging any of my merge requests.
I kept all his original credits including the artwork one:
`Graphics in this plasmoid orginate from [Steampunk orrery](http://lightquick.co.uk/downloads/steampunk-orrery-xwidget.html).`
Unfortunately that link no longer exists. so i just did a short google search till I found something.

Should be pointing to your link now.

Also if you still happen to have the original artwork project and are willing to share. I had to use AI upscaling to make the texture a bit more high-dpi friendly.

**Comment by yereverluvinunclebert** [comment]
Thanks. That old link will be resurrected soon, illness in the family caused the site to be taken down. The DeviantArt one will certainly do in the meantime. I do have the original imagery in the form of the original photoshop PSDs, other than that it is just a set of PNGs that you have already. Pity that the marble tool connection seems to be broken.

Glad you like the old orrery.  I still have it on my Win desktop even today and when I gravitate away from Windows 7 (which I aim to do to avoid Win10/11) then my target is KDE. I may well fork your plasmoid back on course with the original YWE version. One day. 

See the YWE version here - https://www.youtube.com/watch?v=9bLdQIjafvM

**Comment by xyz32** [comment]
If I can use the PSD files to generate a higher res picture then sure, otherwise I guess AI upscaling is the way to go.

As for forking it, sure. The most amount of time I spent on this plasmoid was to completely refactor the code, to have it logically structured, and keep object functionality in one place. Should make it way easier to understand.

**Comment by yereverluvinunclebert** [comment]
Well, you are welcome to the PSD files. I'll need an email address rather than just attaching here.

Any fork is on my wish list but in reality it is already a long list.

**Comment by xyz32** [comment]
I was thinking more if you want to release then under an open licence somewhere. Or create a merge request here and I would gladly make them part of this repo.
Thanks.

**Comment by yereverluvinunclebert** [comment]
Will do shortly!
